version: '3.7'

services:
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: employeerdb
      POSTGRES_DB: employeer
    ports:
      - "5432:5432"